my:
  greeting: Hello World from config server
  list:
    values: One,Two,Three,Four
app:
  name: My app
  descirption: Welcome to ${app.name}

db:
  connection: updated-connection-string-from-config-server
  host: 129.0.0.1
  port: 2400
